### ISSUE TITLE
html-to-markdown plugin 

### ISSUE THREAD

**Issue by JohannesKaufmann** [DeabLabs/urlmd#1]
@cephalization  Hi, I just saw that you are using the html-to-markdown converter and even wrote your own plugin! That's great to hear!

If I am reading it correctly you wrote the plugin to rewrite links.

FYI: You can use `WithDomain` to give the converter the current url. This then gets used to convert *relative* to *absolute* URLs. 

This wasn't previously mentioned in the REAMDE, just fixed that. And I also improved the logic for the domain in the newest version.

```go
markdown, err := htmltomarkdown.ConvertString(input, converter.WithDomain("https://example.com"))
```

Feel free to close this once you have read it... And let me know if you encounter any problems!

**Comment by cephalization** [comment]
I was gonna reach out about that soon haha thanks! Will let you know how it works

**Comment by cephalization** [comment]
@JohannesKaufmann it works great, thanks!
